### ISSUE TITLE
verifySeedPhrase is throwing an exception

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/gaba#11]
This for loop (https://github.com/MetaMask/gaba/blob/master/src/KeyringController.ts#L302) is assuming accounts and testAccounts are objects, but in reality it's an array,.

See example: 
<img width="829" alt="screen shot 2018-08-07 at 11 52 43 pm" src="https://user-images.githubusercontent.com/1247834/43815358-58715eba-9a9d-11e8-8bf6-03a283304b89.png">

**Comment by bitpshr** [comment]
Fixed in 878bdf62accbc3af1c0c83214200faa55c04b518.
